# Site settings
title: Laboratório de Controle de Processos
email: brunno.v@grad.ufsc.br
author: Brunno Vanelli
project_name: control-lab
project_site: https://github.com/bvanelli/control-lab
download_url: https://github.com/bvanelli/control-lab
short_description: >
  <p>Laboratório de Controle de Sistemas</p>
  <p>Desenvolvido com <i class="fa fa-heart"></i> e com código aberto</p>
description: > # this means to ignore newlines until "baseurl:"
    O laboratório de controle de sistemas é um projeto desenvolvido por alunos
    da UFSC para facilitar o aprendizado de sistemas de controle. O projeto conta
    com simulação, montagem e realização de experimentos em sistemas físicos reais.
github_username: bvanelli
baseurl: /control-lab


markdown: kramdown
highlighter: pygments
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      body_color: "primary"
      layout: "page"
      title_icon: fa fa-link

# allowed colors: primary, green, blue, orange, red, pink, purple
